name: Test
on:
  push:
    branches: [main]
jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: npm install
      - name: Set up Env File
        run: npm run env:setup
      - name: Setup Database
        run: npm run db:setup
      - name: Seed Database
        run: npm run db:seed
      - name: Run Tests
        run: npm test
